name:"Deploy Codigofacilito"

on:
  push:
    branches["main"]
jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
     - run: echo "Hacemos puññ del codigo"
     - run: echo "Correr migraciones"
     - run: echo "Generar binario"
     - run: echo "Publicar version"
